### ISSUE TITLE
Console.logging from async mode

### ISSUE THREAD

**Issue by kevinburkeshyp** [interactivecomputing/ijs#1]
hey, thanks for working on this project! it's super neat. 

I'm trying to do an async call and then print some data to the terminal, and I'm a little confused by the example. Boiled down, something like this:

``` javascript
setTimeout(function() { console.log("hello!"); }, 3000);
```

How would I get that console output to show in iPython? 

Thanks!
Kevin

**Comment by kevinburkeshyp** [comment]
Ah, I get that there's a `_.async` callback I can create, but when I try to use it like this:

``` javascript
_.async(function(deferred) {
    setTimeout(function() { 
        console.log("hello!"); 
        deferred.resolve();
    }, 3000);
});
```

I get the following error:

```
ReferenceError: _ is not defined
  at evalmachine.<anonymous>:1:1
  at Object.exports.runInThisContext (vm.js:74:17)
  at run ([eval]:171:19)
  at onMessage ([eval]:75:41)
  at process.emit (events.js:110:17)
  at handleMessage (child_process.js:324:10)
  at Pipe.channel.onread (child_process.js:352:11)
```

However, the console output appears! (I tried a more complicated example and it broke again).

**Comment by nikhilk** [comment]
I am not seeing the "_" is not defined error. What I did see was "setTimeout" is undefined and that was because of missing globals, which I now added.

Thanks for reporting.
